<?php UTIL::Load_Content('headerbanner', 'dynamic')?>
<div class="pagetext">
    <p>This website is a wiki style database for the hardest parts of FromSoftware's 2022 action role-playing game, Elden Ring.
        Our main focus is providing up-to-date content for gamers on all platforms. The content covers a wide array, including how
        to defeat your worst enemy, what builds work best for your play type, and even help users find other members of the community
        to join up with and take down the hardest bosses. We wanted to simply the game and bring the community together in one easy
        to use format.
        <br>
        <br>
        This website is created as a capstone project for Arizona State University's Bachelors in Information Technology. It
        combines SQL database management, cybersecurity initatives, HTML, CSS, and JavaScript coding, and much more.
    </p>
    <br>Meet the team!<br>
    <p>Bernadette Asoanab</p>
    <br>
    <p>Larry Stanfield</p>
    <br>
    <p>Megan Joslin is the website designer. She handles the website look and feel, and controls the webpage coding. She also handles the ongoing changes to the website, including the patch notes section, updating boss help guides as things change, and working with the team to bring new and exciting content to the website.</p>
</div>