<div class="headerbanner">
        <h1><u>Find a Team</u></h1>
    </div>

    <div class="pagetext">
    <p>Looking for a group of players to cruise through the story with or help take down a difficult boss?
        You've come to the right place! Please choose what platform you are on and explore from there. You're
        welcomed to make your own post or comment on an exisiting one!

        <br><hr><br><ul>
        <li><a href=""">Playstation 5</a></li>
        <li><a href=""">Xbox Series X</a></li>
        <li><a href="">Playstation 4</a></li>
        <li><a href="">Xbox One</a></li>
        <li><a href="">Steam</a></li>
        </ul>
    </p>