<h1>Welcome to the Elden Ring Wiki</h1>

<p>To get started, create an account so you can post forum questions, find a team to play with, and browse content freely!
Inside the forum pages, you can find help on defeating a boss, improved item and ability combos for your character type, and
other gameplay tips and tricks.</p>

<div class="updates">
	<h2>Update & Patch Notes</h2>

	<p><B><a href="https://en.bandainamcoent.eu/elden-ring/news/elden-ring-patch-notes-104">Patch 1.04</a></b></p>
	<p><i>We are distributing an update to improve the stability of gameplay and to adjust balance.
	We apologize for the inconvenience, but please apply the latest update before you enjoy the game.</p>
	<p>Targeted Platform: PlayStation 4 / PlayStation 5 / Xbox One / Xbox Series X|S / Steam</i></p>

	<br>

	<p><b><a href="https://en.bandainamcoent.eu/elden-ring/news/elden-ring-update-notes-103">Update Notes 1.03</a></b></p>
	<p><i>We are distributing this new update to fix a bug in patch 1.03</p>
	<p>Targeted Platform: PlayStation 4 / PlayStation 5 / Xbox One / Xbox Series X|S / Steam</i></p>

	<br>

	<p><B><a href="https://en.bandainamcoent.eu/elden-ring/news/elden-ring-patch-notes-1032">Patch 1.03.2</a></b></p>
	<p><i>We are distributing this new update to fix several bugs in patch 1.03
	We apologize for the inconvenience, but please apply the latest update before you enjoy the game.</p>
	<p>Targeted Platform: PlayStation 4 / PlayStation 5 / Xbox One / Xbox Series X|S / Steam</i></p>

	<br>

	<p><b><a href="https://en.bandainamcoent.eu/elden-ring/news/elden-ring-patch-notes-version-103">Patch 1.03</a></b></p>
	<p><i>We are distributing an update to improve the stability of gameplay and to adjust balance.
	We apologize for the inconvenience, but please apply the latest update before you enjoy the game.</p>
	<p>Targeted platform: PlayStation 4 / PlayStation 5 / Xbox One / Xbox Series X|S / Steam</i></p>

	<br>

	<p><b><a href="https://en.bandainamcoent.eu/elden-ring/news/elden-ring-patch-notes-version-102">Patch 1.02</a></b></p>
	<p><i>We have started distributing a patch to improve the stability of the gameplay. We apologize for the inconvenience, but please apply the latest patch before playing the game. 
	When this patch is applied, the version on the bottom right of the title screen will read as follows: </i></p>

	<p><i>App Ver. 1.02</i></p>
	<p><i>Regulation Ver. 1.02.1</i></p>
</div>