<?php UTIL::Load_Content('headerbanner', 'dynamic')?>
<div class="pagetext">
    <form method="post" action="/auth" id="login-form">

        <fieldset>
            <label for="username">Username</label>
            <input name="username" type="text" placeholder="username"/>
        </fieldset>

        <fieldset>
            <label for="password">Password</label>
            <input name="password" type="password" placeholder="password"/>
        </fieldset>

        <fieldset>
            <input name="submit" type="submit" value="login">
            <input name="remember_me" type="checkbox" /> Remember me
        </fieldset>

        <fieldset>
            <button name="cancel">Cancel</button>
            Forgot <a href="/forgot-password">Password</a>
        </fieldset>

        <input type="hidden" name="mode" value="login">

    </form>
</div>