                <div id="header">
                    <div class="top_image">
                        <a href="/<?=LANG::Get('this');?>/" title="Elden Ring Wiki">
                            <img src="/site/pix/micro_mvc.png">
                        </a>
                    </div>
                    <ul>
                        <li><a href="index.html">Home</a></li>
                        <li><a href="find_a_team.html">Find a Team</a></li>
                        <li><a href="improve_your_game.html">Improve Your Game</a></li>
                        <li><a href="about.html">About</a></li>
                        <li><a href="login_page.html">Login</a></li>
                    </ul>
                    <div class="motto"><?=UTIL::Load_Content('motto', 'static');?></div>
                </div>
